name: Actions Workflow
#on: [push, pull_request]
on:
  #repository_dispatch:
  #  types: [build]
  #schedule:
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"
  push: #pull_request
    branches:
      - master
  #pull_request:
  #  types: [closed, assigned, opened, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA #ID commit
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          #git clone git@github:$GITHUB_REPOSITORY
          #git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        #uses: actions/hello-world-javascript-action@714607abe96dc33dd6031e1c1745a12839cef5e1 #COMMIT
        #uses: actions/hello-world-javascript-action@v1.1 #RELEASE
        #uses: actions/hello-world-javascript-action@master #BRANCH
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Gretting Time
        run: echo "${{ steps.greet.outputs.time }}" #value return step output value of time
