name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
      steps:
        - name: Simple JS Action
          id: greet
          #uses: actions/hello-world-javascript-action@714607abe96dc33dd6031e1c1745a12839cef5e1 #COMMIT
          #uses: actions/hello-world-javascript-action@v1.1 #RELEASE
          #uses: actions/hello-world-javascript-action@master #BRANCH
          uses: actions/hello-world-javascript-action@master
          with:
            who-to-greet: John
        #- name: Log Gretting Time
        #  run: echo "${{ steps.greet.outputs.time }}" #value return step output value of time
